program Prontto;

uses
  Forms,
  UPessoa in 'uPessoa.pas' {fPessoa},
  UDm1 in 'UDm1.pas' {Dm1: TDataModule},
  UDmCons in 'UDmCons.pas' {DmCons: TDataModule},
  UMenu in 'UMenu.pas' {fMenu},
  UPais in 'UPais.pas' {fPais},
  UGrupo in 'UGrupo.pas' {fGrupo},
  USitTributaria in 'USitTributaria.pas' {fSitTributaria},
  UClasFiscal in 'UClasFiscal.pas' {fClasFiscal},
  UNatOperacao in 'UNatOperacao.pas' {fNatOperacao},
  UProduto in 'UProduto.pas' {fProduto},
  UCondPgto in 'UCondPgto.pas' {fCondPgto},
  UTipoCobranca in 'UTipoCobranca.pas' {fTipoCobranca},
  UUF in 'UUF.pas' {fUF},
  UMaoObra in 'UMaoObra.pas' {fMaoObra},
  UEmpresa in 'UEmpresa.pas' {fEmpresa},
  UBanco in 'UBanco.pas' {fBanco},
  UCondPgtoIt in 'UCondPgtoIt.pas' {fCondPgtoIt},
  UProdutoIt in 'UProdutoIt.pas' {fProdutoIt},
  UEstoque in 'UEstoque.pas' {fEstoque},
  UProdutoHist in 'UProdutoHist.pas' {fProdutoHist},
  UParametros in 'UParametros.pas' {fParametros},
  UContasPagar in 'UContasPagar.pas' {fContasPagar},
  UPrevCheques in 'UPrevCheques.pas' {fPrevCheques},
  UMovFinanceiro in 'UMovFinanceiro.pas' {fMovFinanceiro},
  UMovFinanceiroIt in 'UMovFinanceiroIt.pas' {fMovFinanceiroIt},
  UContasReceber in 'UContasReceber.pas' {fContasReceber},
  UDevolucaoRec in 'UDevolucaoRec.pas' {fDevolucaoRec},
  UDevolucaoPag in 'UDevolucaoPag.pas' {fDevolucaoPag},
  uSobre in 'uSobre.pas' {fSobre},
  uPortaImpressao in 'uPortaImpressao.pas' {fPortaImpressao},
  UPessoaRel in 'UPessoaRel.pas' {fPessoaRel},
  UMovFinanceiroRel in 'UMovFinanceiroRel.pas' {fMovFinanceiroRel},
  UPedidoRel in 'UPedidoRel.pas' {fPedidoRel},
  UContasReceberRel in 'UContasReceberRel.pas' {fContasReceberRel},
  UContasReceberDet in 'UContasReceberDet.pas' {fContasReceberDet},
  UContasReceberPgto in 'UContasReceberPgto.pas' {fContasReceberPgto},
  UJuros in 'UJuros.pas' {fJuros},
  UFluxoFuturo in 'UFluxoFuturo.pas' {fFluxoFuturo},
  uLogin in 'uLogin.pas' {fLogin},
  UUsuario in 'UUsuario.pas' {fUsuario},
  UContasPagarRel in 'UContasPagarRel.pas' {fContasPagarRel},
  UContasPagarDet in 'UContasPagarDet.pas' {fContasPagarDet},
  USenha in 'USenha.pas' {fSenha},
  UAutorizacao in 'UAutorizacao.pas' {fAutorizacao},
  UEstoqueRel in 'UEstoqueRel.pas' {fEstoqueRel},
  UConsComissaoVend in 'UConsComissaoVend.pas' {fConsComissaoVend},
  UOrcamentoPrev in 'UOrcamentoPrev.pas' {fOrcamentoPrev},
  UOrcamentoPrevRel in 'UOrcamentoPrevRel.pas' {fOrcamentoPrevRel},
  UComissaoRel in 'UComissaoRel.pas' {fComissaoRel},
  UPedidoPrev in 'UPedidoPrev.pas' {fPedidoPrev},
  UPedidoPrevRel in 'UPedidoPrevRel.pas' {fPedidoPrevRel},
  UContasReceberCliente in 'UContasReceberCliente.pas' {fContasReceberCliente},
  UContasReceberClienteRel in 'UContasReceberClienteRel.pas' {fContasReceberClienteRel},
  uPlanoSaudeC in 'uPlanoSaudeC.pas' {fPlanoSaudeC},
  uPlanoSaude in 'uPlanoSaude.pas' {fPlanoSaude},
  uServico in 'uServico.pas' {fServico},
  uServicoC in 'uServicoC.pas' {fServicoC},
  uAnamnese in 'uAnamnese.pas' {fAnamnese},
  uAnamneseC in 'uAnamneseC.pas' {fAnamneseC},
  uFormaPgtoC in 'uFormaPgtoC.pas' {fFormaPgtoC},
  uFormaPgto in 'uFormaPgto.pas' {fFormaPgto},
  uPessoac in 'uPessoac.pas' {fPessoaC},
  uCidadeC in 'uCidadeC.pas' {fCidadeC},
  uCidade in 'uCidade.pas' {fCidade},
  UBoletos in 'UBoletos.pas' {fBoletos},
  uTelefone in 'uTelefone.pas' {fTelefone},
  uPessoaAnamnese in 'uPessoaAnamnese.pas' {fPessoaAnamnese},
  uPessoaServico in 'uPessoaServico.pas' {fPessoaServico},
  uPessoaAtendimento in 'uPessoaAtendimento.pas' {fPessoaAtendimento},
  uOrcamentoInstC in 'uOrcamentoInstC.pas' {fOrcamentoInstC},
  uOrcamentoInst in 'uOrcamentoInst.pas' {fOrcamentoInst},
  uOrcamentoProd in 'uOrcamentoProd.pas' {fOrcamentoProd},
  uOrcServPerm in 'uOrcServPerm.pas' {fOrcServPerm},
  URelBoletos in 'URelBoletos.pas' {fRelBoletos},
  uAlarme in 'uAlarme.pas' {fAlarme},
  uCustoHomem in 'uCustoHomem.pas' {fCustoHomem},
  uEscalaC in 'uEscalaC.pas' {fEscalaC},
  uEscala in 'uEscala.pas' {fEscala},
  uImport in 'uImport.pas' {fImport},
  uClausulaC in 'uClausulaC.pas' {fClausulaC},
  uClausula in 'uClausula.pas' {fClausula},
  uOrcamentoClausula in 'uOrcamentoClausula.pas' {fOrcamentoClausula},
  UGBoleto in 'UGBoleto.pas' {fGBoleto},
  UBcoItau in 'UBcoItau.pas' {fBcoItau},
  UMovAvulsoIt in 'UMovAvulsoIt.pas' {fMovAvulsoIt},
  UMovAvulso in 'UMovAvulso.pas' {fMovAvulso},
  UGeraMovMensal in 'UGeraMovMensal.pas' {fGeraMovMensal},
  UArqRetornoItau in 'UArqRetornoItau.pas' {fArqRetornoItau},
  UContasPagarPgto in 'UContasPagarPgto.pas' {fContasPagarPgto},
  UPrevBoleto2 in 'UPrevBoleto2.pas' {fPrevBoleto2},
  uRelBoletoItau in 'uRelBoletoItau.pas' {fRelBoletoItau},
  uCentroCustoC in 'uCentroCustoC.pas' {fCentroCustoC},
  uCentroCusto in 'uCentroCusto.pas' {fCentroCusto},
  UPrevPessoa in 'UPrevPessoa.pas' {fPrevPessoa},
  SelfPrintDefs in 'SelfPrintDefs.pas',
  SendMail in 'SendMail.pas',
  SendMailOptions in 'SendMailOptions.pas' {FormSendMailOptions},
  UPedidoRelAvulso in 'UPedidoRelAvulso.pas' {fPedidoRelAvulso},
  UPedidoRelPermanente in 'UPedidoRelPermanente.pas' {fPedidoRelPermanente},
  UPedidoRelPermanenteAprov in 'UPedidoRelPermanenteAprov.pas' {fPedidoRelPermanenteAprov},
  UConsCentroCusto in 'UConsCentroCusto.pas' {fConsCentroCusto},
  UAtendimento in 'UAtendimento.pas' {fAtendimento},
  URelConsCCusto in 'URelConsCCusto.pas' {fRelConsCCusto},
  URelReciboCPagar in 'URelReciboCPagar.pas' {fRelReciboCPagar},
  URelRecibo in 'URelRecibo.pas' {fRelRecibo},
  URecibo in 'URecibo.pas' {fRecibo},
  URelReciboCob in 'URelReciboCob.pas' {fRelReciboCob},
  URelRecibo2 in 'URelRecibo2.pas' {fRelRecibo2},
  UPrevRecibo2 in 'UPrevRecibo2.pas' {fPrevRecibo2},
  uBinaHistorico in 'uBinaHistorico.pas' {fBinaHistorico},
  URelRecibo3 in 'URelRecibo3.pas' {fRelRecibo3},
  uOrcServ in 'uOrcServ.pas' {fOrcServ},
  URelPessoaFicha in 'URelPessoaFicha.pas' {fRelPessoaFicha},
  uEventos in 'uEventos.pas' {fEventos},
  uEventosC in 'uEventosC.pas' {fEventosC},
  UValores in 'UValores.pas' {fValores},
  UValoresC in 'UValoresC.pas' {fValoresC},
  UMovFuncionario in 'UMovFuncionario.pas' {fMovFuncionario},
  rsDBUtils in '..\rslib\Nova\rsDBUtils.pas',
  URelPessoas in 'URelPessoas.pas' {fRelPessoas},
  UCurso in 'UCurso.pas' {fCurso},
  uPessoaCurso in 'uPessoaCurso.pas' {fPessoaCurso},
  URelPessoasContrato in 'URelPessoasContrato.pas' {fRelPessoasContrato},
  uContasReceberCentroC in 'uContasReceberCentroC.pas' {fContasReceberCCusto},
  uPessoaEmpresas in 'uPessoaEmpresas.pas' {fPessoaEmpresas},
  uPrevQNC in 'uPrevQNC.pas' {fPrevQNC},
  uRelQNC in 'uRelQNC.pas' {fRelQNC},
  uRelComprovante in 'uRelComprovante.pas' {fRelComprovante},
  UBcoSicredi in 'UBcoSicredi.pas' {fBcoSicredi},
  UCobSicredAlt in 'UCobSicredAlt.pas' {fCobSicredAlt},
  UArqRetornoSicred in 'UArqRetornoSicred.pas' {fArqRetornoSicred},
  uRelBoletoSicred in 'uRelBoletoSicred.pas' {fRelBoletoSicred},
  UCobSicred in 'UCobSicred.pas' {fCobSicred},
  UPrevDuplicatas in 'UPrevDuplicatas.pas' {fPrevDuplicatas},
  URelDuplicata in 'URelDuplicata.pas' {fRelDuplicata},
  uPessoaServicoContrato in 'uPessoaServicoContrato.pas' {fPessoaServicoContrato},
  uVincendo in 'uVincendo.pas' {fVincendo},
  uDiarioC in 'uDiarioC.pas' {fDiarioC},
  uDiario in 'uDiario.pas' {fDiario},
  uViaturaC in 'uViaturaC.pas' {fViaturaC},
  uViatura in 'uViatura.pas' {fViatura},
  uDmDiario in 'uDmDiario.pas' {dmDiario: TDataModule},
  uBairroC in 'uBairroC.pas' {fBairroC},
  uBairro in 'uBairro.pas' {fBairro},
  uAgente in 'uAgente.pas' {fAgente},
  uAgenteC in 'uAgenteC.pas' {fAgenteC},
  uDiarioViatura in 'uDiarioViatura.pas' {fDiarioViatura},
  uDiarioAlarme in 'uDiarioAlarme.pas' {fDiarioAlarme},
  uDiarioEspecial in 'uDiarioEspecial.pas' {fDiarioEspecial},
  uDiarioCamera in 'uDiarioCamera.pas' {fDiarioCamera},
  uDiarioRevisado in 'uDiarioRevisado.pas' {fDiarioRevisado},
  uDiarioBairro in 'uDiarioBairro.pas' {fDiarioBairro},
  uDiarioRonda in 'uDiarioRonda.pas' {fDiarioRonda},
  uDiarioPortaria in 'uDiarioPortaria.pas' {fDiarioPortaria},
  uCursoDisciplina in 'uCursoDisciplina.pas' {fCursoDisciplina},
  uDisciplinaC in 'uDisciplinaC.pas' {fDisciplinasC},
  uDisciplina in 'uDisciplina.pas' {fDisciplina},
  uCursoC in 'uCursoC.pas' {fCursoC},
  reinit in 'reinit.pas',
  uEmissaoBoleto in 'uEmissaoBoleto.pas' {fEmissaoBoleto},
  uNotasC in 'uNotasC.pas' {fNotasC},
  uRelNotas in 'uRelNotas.pas' {fRelNotas},
  URelArqRetSicred in 'URelArqRetSicred.pas' {fRelArqRetSicred},
  uCelular in 'uCelular.pas' {fCelular},
  uCelularC in 'uCelularC.pas' {fCelularC},
  uDiarioCelular in 'uDiarioCelular.pas' {fDiarioCelular},
  uEditor in 'uEditor.pas' {fEditor},
  uEscalaDiaria in 'uEscalaDiaria.pas' {fEscalaDiaria},
  uEscalaDiariaC in 'uEscalaDiariaC.pas' {fEscalaDiariaC},
  uDmEscala in 'uDmEscala.pas' {dmEscala: TDataModule},
  uEscalaAlerta in 'uEscalaAlerta.pas' {fEscalaAlerta},
  uDiarioR in 'uDiarioR.pas' {fDiarioR},
  LogTypes in '..\logs\src\LogTypes.pas',
  LogProvider in '..\logs\src\LogProvider.pas',
  rsDataSetError in '..\rslib\rsDataSetError.pas',
  uUtil in 'UUtil.pas',
  uExtratoSEG in 'uExtratoSEG.pas' {fExtratoSEG},
  uCertificadoR in 'uCertificadoR.pas' {fCertificadoR},
  uCertificadoC in 'uCertificadoC.pas' {fCertificadoC},
  uCertificadoR2 in 'uCertificadoR2.pas' {fCertificadoR2},
  uCurriculoR in 'uCurriculoR.pas' {fCurriculoR},
  UDMRel in 'UDMRel.pas' {DmRel: TDataModule},
  uCaptura in 'WebCam\uCaptura.pas' {fCaptura},
  uFotoUtils in 'WebCam\uFotoUtils.pas',
  uImportaAlunos in 'uImportaAlunos.pas' {fImportaAlunos},
  uRelAtacLista in 'uRelAtacLista.pas' {fRelAtacLista},
  uCobRemessa in 'uCobRemessa.pas' {fCobRemessa},
  uDmCobranca in 'uDmCobranca.pas' {dmCobranca: TDataModule},
  uCobRetorno in 'UCobRetorno.pas' {fCobRetorno},
  uPrevVendaCurso in 'uPrevVendaCurso.pas' {fPrevVendaCurso},
  URelRemessa in 'URelRemessa.pas' {fRelRemessa};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Prontto Segurança';
  Application.CreateForm(TfMenu, fMenu);
  Application.Run;
end.
