unit uDmDiario;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TdmDiario = class(TDataModule)
    sdsDiario: TSQLDataSet;
    dspDiario: TDataSetProvider;
    cdsDiario: TClientDataSet;
    dsDiario: TDataSource;
    sdsDiarioID: TIntegerField;
    sdsDiarioDATA: TDateField;
    sdsDiarioTURNO: TStringField;
    sdsDiarioREVISADO_HORA: TTimeField;
    sdsDiarioREVISADO_POR: TStringField;
    sdsDiarioOPERADOR_RADIO: TStringField;
    sdsDiarioOBS: TMemoField;
    cdsDiarioID: TIntegerField;
    cdsDiarioDATA: TDateField;
    cdsDiarioTURNO: TStringField;
    cdsDiarioREVISADO_HORA: TTimeField;
    cdsDiarioREVISADO_POR: TStringField;
    cdsDiarioOPERADOR_RADIO: TStringField;
    cdsDiarioOBS: TMemoField;
    dsmDiario: TDataSource;
    sdsDiarioViatura: TSQLDataSet;
    cdsDiarioViatura: TClientDataSet;
    dsDiarioViatura: TDataSource;
    sdsDiarioBairro: TSQLDataSet;
    cdsDiarioBairro: TClientDataSet;
    dsDiarioBairro: TDataSource;
    sdsDiarioRonda: TSQLDataSet;
    cdsDiarioRonda: TClientDataSet;
    dsDiarioRonda: TDataSource;
    sdsDiarioAlarme: TSQLDataSet;
    cdsDiarioAlarme: TClientDataSet;
    dsDiarioAlarme: TDataSource;
    sdsDiarioBairroDIARIO_ID: TIntegerField;
    sdsDiarioBairroBAIRRO_ID: TIntegerField;
    sdsDiarioBairroVIATURA_ID: TIntegerField;
    sdsDiarioBairroHORA: TTimeField;
    sdsDiarioBairroOBS: TStringField;
    cdsDiarioBairroDIARIO_ID: TIntegerField;
    cdsDiarioBairroBAIRRO_ID: TIntegerField;
    cdsDiarioBairroVIATURA_ID: TIntegerField;
    cdsDiarioBairroHORA: TTimeField;
    cdsDiarioBairroOBS: TStringField;
    cdsDiariosdsDiarioBairro: TDataSetField;
    sdsDiarioViaturaDIARIO_ID: TIntegerField;
    sdsDiarioViaturaVIATURA_ID: TIntegerField;
    sdsDiarioViaturaKM_INICIAL: TIntegerField;
    sdsDiarioViaturaKM_FINAL: TIntegerField;
    sdsDiarioViaturaOBS: TStringField;
    cdsDiarioViaturaDIARIO_ID: TIntegerField;
    cdsDiarioViaturaVIATURA_ID: TIntegerField;
    cdsDiarioViaturaKM_INICIAL: TIntegerField;
    cdsDiarioViaturaKM_FINAL: TIntegerField;
    cdsDiarioViaturaOBS: TStringField;
    cdsDiariosdsDiarioViatura: TDataSetField;
    sdsDiarioRondaDIARIO_ID: TIntegerField;
    sdsDiarioRondaPESSOA_ID: TIntegerField;
    sdsDiarioRondaVIATURA_ID: TIntegerField;
    sdsDiarioRondaHORA: TTimeField;
    sdsDiarioRondaOBS: TStringField;
    cdsDiarioRondaDIARIO_ID: TIntegerField;
    cdsDiarioRondaPESSOA_ID: TIntegerField;
    cdsDiarioRondaVIATURA_ID: TIntegerField;
    cdsDiarioRondaHORA: TTimeField;
    cdsDiarioRondaOBS: TStringField;
    sdsDiarioAlarmeDIARIO_ID: TIntegerField;
    sdsDiarioAlarmePESSOA_ID: TIntegerField;
    sdsDiarioAlarmeID: TIntegerField;
    sdsDiarioAlarmeAGENTE_ID: TIntegerField;
    sdsDiarioAlarmeHORA: TTimeField;
    cdsDiarioAlarmeDIARIO_ID: TIntegerField;
    cdsDiarioAlarmePESSOA_ID: TIntegerField;
    cdsDiarioAlarmeID: TIntegerField;
    cdsDiarioAlarmeAGENTE_ID: TIntegerField;
    cdsDiarioAlarmeHORA: TTimeField;
    cdsDiariosdsDiarioAlarme: TDataSetField;
    cdsDiariosdsDiarioRonda: TDataSetField;
    sdsDiarioAlarmeSA: TStringField;
    sdsDiarioAlarmeCA: TStringField;
    cdsDiarioAlarmeSA: TStringField;
    cdsDiarioAlarmeCA: TStringField;
    sdsDiarioAlarmeAPBM: TStringField;
    cdsDiarioAlarmeAPBM: TStringField;
    sdsDiarioEspecial: TSQLDataSet;
    cdsDiarioEspecial: TClientDataSet;
    dsDiarioEspecial: TDataSource;
    sdsDiarioEspecialDIARIO_ID: TIntegerField;
    sdsDiarioEspecialCLIENTE_ID: TIntegerField;
    sdsDiarioEspecialID: TIntegerField;
    sdsDiarioEspecialMOTIVO: TStringField;
    sdsDiarioEspecialAGENTE_ID: TIntegerField;
    sdsDiarioEspecialSA: TStringField;
    sdsDiarioEspecialPROCEDIMENTO: TStringField;
    sdsDiarioEspecialAPBM: TStringField;
    cdsDiarioEspecialDIARIO_ID: TIntegerField;
    cdsDiarioEspecialCLIENTE_ID: TIntegerField;
    cdsDiarioEspecialID: TIntegerField;
    cdsDiarioEspecialMOTIVO: TStringField;
    cdsDiarioEspecialAGENTE_ID: TIntegerField;
    cdsDiarioEspecialSA: TStringField;
    cdsDiarioEspecialPROCEDIMENTO: TStringField;
    cdsDiarioEspecialAPBM: TStringField;
    sdsDiarioCamera: TSQLDataSet;
    cdsDiarioCamera: TClientDataSet;
    dsDiarioCamera: TDataSource;
    sdsDiarioCameraDIARIO_ID: TIntegerField;
    sdsDiarioCameraCLIENTE_ID: TIntegerField;
    sdsDiarioCameraID: TIntegerField;
    sdsDiarioCameraHORA_QUEDA: TTimeField;
    sdsDiarioCameraMENSAGEM: TStringField;
    sdsDiarioCameraHORA_RETORNO: TTimeField;
    sdsDiarioCameraOBS: TStringField;
    cdsDiariosdsDiarioCamera: TDataSetField;
    cdsDiariosdsDiarioEspecial: TDataSetField;
    cdsDiarioCameraDIARIO_ID: TIntegerField;
    cdsDiarioCameraCLIENTE_ID: TIntegerField;
    cdsDiarioCameraID: TIntegerField;
    cdsDiarioCameraHORA_QUEDA: TTimeField;
    cdsDiarioCameraMENSAGEM: TStringField;
    cdsDiarioCameraHORA_RETORNO: TTimeField;
    cdsDiarioCameraOBS: TStringField;
    sdsDiarioViaturaVIATURA: TStringField;
    sdsDiarioViaturaAGENTE: TStringField;
    cdsDiarioViaturaVIATURA: TStringField;
    cdsDiarioViaturaAGENTE: TStringField;
    sdsDiarioViaturaAGENTE_ID: TIntegerField;
    cdsDiarioViaturaAGENTE_ID: TIntegerField;
    sdsDiarioAlarmeCLIENTE: TStringField;
    sdsDiarioAlarmeAGENTE: TStringField;
    cdsDiarioAlarmeCLIENTE: TStringField;
    cdsDiarioAlarmeAGENTE: TStringField;
    sdsDiarioEspecialCLIENTE: TStringField;
    sdsDiarioEspecialAGENTE: TStringField;
    cdsDiarioEspecialCLIENTE: TStringField;
    cdsDiarioEspecialAGENTE: TStringField;
    sdsDiarioCameraCLIENTE: TStringField;
    cdsDiarioCameraCLIENTE: TStringField;
    sdsDiarioBairroBAIRRO: TStringField;
    cdsDiarioBairroBAIRRO: TStringField;
    sdsDiarioBairroPLACA: TStringField;
    cdsDiarioBairroPLACA: TStringField;
    sdsDiarioDIARIO_ID: TIntegerField;
    cdsDiarioDIARIO_ID: TIntegerField;
    sdsDiarioOBS_REVISAO: TMemoField;
    cdsDiarioOBS_REVISAO: TMemoField;
    sdsDiarioRondaCLIENTE: TStringField;
    sdsDiarioRondaPLACA: TStringField;
    cdsDiarioRondaCLIENTE: TStringField;
    cdsDiarioRondaPLACA: TStringField;
    sdsDiarioPortaria: TSQLDataSet;
    cdsDiarioPortaria: TClientDataSet;
    dsDiarioPortaria: TDataSource;
    sdsDiarioPortariaDIARIO_ID: TIntegerField;
    sdsDiarioPortariaID: TIntegerField;
    sdsDiarioPortariaCLIENTE_ID: TIntegerField;
    sdsDiarioPortariaOBS: TStringField;
    sdsDiarioPortariaCLIENTE: TStringField;
    cdsDiariosdsDiarioPortaria: TDataSetField;
    cdsDiarioPortariaDIARIO_ID: TIntegerField;
    cdsDiarioPortariaID: TIntegerField;
    cdsDiarioPortariaCLIENTE_ID: TIntegerField;
    cdsDiarioPortariaOBS: TStringField;
    cdsDiarioPortariaCLIENTE: TStringField;
    sdsDiarioRV_ALARME: TStringField;
    sdsDiarioRV_ESPECIAL: TStringField;
    sdsDiarioRV_BAIRRO: TStringField;
    sdsDiarioRV_CAMERA: TStringField;
    sdsDiarioRV_PORTARIA: TStringField;
    sdsDiarioRV_RONDA: TStringField;
    sdsDiarioRV_VIATURA: TStringField;
    sdsDiarioFC_ALARME: TStringField;
    sdsDiarioFC_ESPECIAL: TStringField;
    sdsDiarioFC_BAIRRO: TStringField;
    sdsDiarioFC_CAMERA: TStringField;
    sdsDiarioFC_PORTARIA: TStringField;
    sdsDiarioFC_RONDA: TStringField;
    sdsDiarioFC_VIATURA: TStringField;
    cdsDiarioRV_ALARME: TStringField;
    cdsDiarioRV_ESPECIAL: TStringField;
    cdsDiarioRV_BAIRRO: TStringField;
    cdsDiarioRV_CAMERA: TStringField;
    cdsDiarioRV_PORTARIA: TStringField;
    cdsDiarioRV_RONDA: TStringField;
    cdsDiarioRV_VIATURA: TStringField;
    cdsDiarioFC_ALARME: TStringField;
    cdsDiarioFC_ESPECIAL: TStringField;
    cdsDiarioFC_BAIRRO: TStringField;
    cdsDiarioFC_CAMERA: TStringField;
    cdsDiarioFC_PORTARIA: TStringField;
    cdsDiarioFC_RONDA: TStringField;
    cdsDiarioFC_VIATURA: TStringField;
    sdsDiarioOK_ALARME: TStringField;
    sdsDiarioOK_BAIRRO: TStringField;
    sdsDiarioOK_CAMERA: TStringField;
    sdsDiarioOK_ESPECIAL: TStringField;
    sdsDiarioOK_PORTARIA: TStringField;
    sdsDiarioOK_RONDA: TStringField;
    sdsDiarioOK_VIATURA: TStringField;
    cdsDiarioOK_ALARME: TStringField;
    cdsDiarioOK_BAIRRO: TStringField;
    cdsDiarioOK_CAMERA: TStringField;
    cdsDiarioOK_ESPECIAL: TStringField;
    cdsDiarioOK_PORTARIA: TStringField;
    cdsDiarioOK_RONDA: TStringField;
    cdsDiarioOK_VIATURA: TStringField;
    sdsDiarioRondaTIPO: TStringField;
    cdsDiarioRondaTIPO: TStringField;
    sdsDiarioBairroTIPO: TStringField;
    cdsDiarioBairroTIPO: TStringField;
    cdsDiarioViaturaclKmTotal: TIntegerField;
    sdsDiarioCelular: TSQLDataSet;
    cdsDiarioCelular: TClientDataSet;
    dsDiarioCelular: TDataSource;
    sdsDiarioCelularDIARIO_ID: TIntegerField;
    sdsDiarioCelularCELULAR_ID: TIntegerField;
    sdsDiarioCelularCREDITO: TFMTBCDField;
    sdsDiarioCelularOPERADORA: TStringField;
    sdsDiarioCelularNUMERO: TStringField;
    cdsDiariosdsDiarioCelular: TDataSetField;
    cdsDiarioCelularDIARIO_ID: TIntegerField;
    cdsDiarioCelularCELULAR_ID: TIntegerField;
    cdsDiarioCelularCREDITO: TFMTBCDField;
    cdsDiarioCelularOPERADORA: TStringField;
    cdsDiarioCelularNUMERO: TStringField;
    sdsDiarioPortariaHORA_INI: TTimeField;
    sdsDiarioPortariaHORA_FIM: TTimeField;
    cdsDiarioPortariaHORA_INI: TTimeField;
    cdsDiarioPortariaHORA_FIM: TTimeField;
    sdsDiarioPortariaAGENTE_ID: TIntegerField;
    cdsDiarioPortariaAGENTE_ID: TIntegerField;
    sdsDiarioPortariaAGENTE: TStringField;
    cdsDiarioPortariaAGENTE: TStringField;
    sdsDiarioPortariaHR_CHEGADA: TTimeField;
    sdsDiarioPortariaHR_SAIDA: TTimeField;
    cdsDiarioPortariaHR_CHEGADA: TTimeField;
    cdsDiarioPortariaHR_SAIDA: TTimeField;
    sdsResumo: TSQLDataSet;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    DateField1: TDateField;
    StringField1: TStringField;
    TimeField1: TTimeField;
    StringField2: TStringField;
    StringField3: TStringField;
    MemoField1: TMemoField;
    MemoField2: TMemoField;
    StringField4: TStringField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    StringField10: TStringField;
    StringField11: TStringField;
    StringField12: TStringField;
    StringField13: TStringField;
    StringField14: TStringField;
    StringField15: TStringField;
    StringField16: TStringField;
    StringField17: TStringField;
    StringField18: TStringField;
    StringField19: TStringField;
    StringField20: TStringField;
    StringField21: TStringField;
    StringField22: TStringField;
    StringField23: TStringField;
    StringField24: TStringField;
    dspResumo: TDataSetProvider;
    cdsResumo: TClientDataSet;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    DateField2: TDateField;
    StringField25: TStringField;
    TimeField2: TTimeField;
    StringField26: TStringField;
    StringField27: TStringField;
    MemoField3: TMemoField;
    DataSetField1: TDataSetField;
    DataSetField2: TDataSetField;
    DataSetField3: TDataSetField;
    DataSetField4: TDataSetField;
    DataSetField5: TDataSetField;
    DataSetField6: TDataSetField;
    DataSetField7: TDataSetField;
    DataSetField8: TDataSetField;
    MemoField4: TMemoField;
    StringField28: TStringField;
    StringField29: TStringField;
    StringField30: TStringField;
    StringField31: TStringField;
    StringField32: TStringField;
    StringField33: TStringField;
    StringField34: TStringField;
    StringField35: TStringField;
    StringField36: TStringField;
    StringField37: TStringField;
    StringField38: TStringField;
    StringField39: TStringField;
    StringField40: TStringField;
    StringField41: TStringField;
    StringField42: TStringField;
    StringField43: TStringField;
    StringField44: TStringField;
    StringField45: TStringField;
    StringField46: TStringField;
    StringField47: TStringField;
    StringField48: TStringField;
    dsResumo: TDataSource;
    sdsViatura: TSQLDataSet;
    dspViatura: TDataSetProvider;
    cdsViatura: TClientDataSet;
    dsViatura: TDataSource;
    sdsViaturaID: TIntegerField;
    sdsViaturaATIVA: TStringField;
    sdsViaturaPLACA: TStringField;
    sdsViaturaKM: TIntegerField;
    cdsViaturaID: TIntegerField;
    cdsViaturaATIVA: TStringField;
    cdsViaturaPLACA: TStringField;
    cdsViaturaKM: TIntegerField;
    sdsDiarioCons: TSQLDataSet;
    sdsDiarioConsID: TIntegerField;
    sdsDiarioConsDATA: TDateField;
    sdsDiarioConsTURNO: TStringField;
    sdsDiarioConsREVISADO_HORA: TTimeField;
    sdsDiarioConsREVISADO_POR: TStringField;
    sdsDiarioConsOPERADOR: TStringField;
    sdsDiarioConsOBS: TMemoField;
    sdsDiarioConsRV_ALARME: TStringField;
    sdsDiarioConsRV_ESPECIAL: TStringField;
    sdsDiarioConsRV_BAIRRO: TStringField;
    sdsDiarioConsRV_CAMERA: TStringField;
    sdsDiarioConsRV_PORTARIA: TStringField;
    sdsDiarioConsRV_RONDA: TStringField;
    sdsDiarioConsRV_VIATURA: TStringField;
    sdsDiarioConsFC_ALARME: TStringField;
    sdsDiarioConsFC_ESPECIAL: TStringField;
    sdsDiarioConsFC_BAIRRO: TStringField;
    sdsDiarioConsFC_CAMERA: TStringField;
    sdsDiarioConsFC_PORTARIA: TStringField;
    sdsDiarioConsFC_RONDA: TStringField;
    sdsDiarioConsFC_VIATURA: TStringField;
    dspDiarioCons: TDataSetProvider;
    cdsDiarioCons: TClientDataSet;
    cdsDiarioConsID: TIntegerField;
    cdsDiarioConsDATA: TDateField;
    cdsDiarioConsTURNO: TStringField;
    cdsDiarioConsREVISADO_HORA: TTimeField;
    cdsDiarioConsREVISADO_POR: TStringField;
    cdsDiarioConsOPERADOR: TStringField;
    cdsDiarioConsOBS: TMemoField;
    cdsDiarioConsRV_ALARME: TStringField;
    cdsDiarioConsRV_ESPECIAL: TStringField;
    cdsDiarioConsRV_BAIRRO: TStringField;
    cdsDiarioConsRV_CAMERA: TStringField;
    cdsDiarioConsRV_PORTARIA: TStringField;
    cdsDiarioConsRV_RONDA: TStringField;
    cdsDiarioConsRV_VIATURA: TStringField;
    cdsDiarioConsFC_ALARME: TStringField;
    cdsDiarioConsFC_ESPECIAL: TStringField;
    cdsDiarioConsFC_BAIRRO: TStringField;
    cdsDiarioConsFC_CAMERA: TStringField;
    cdsDiarioConsFC_PORTARIA: TStringField;
    cdsDiarioConsFC_RONDA: TStringField;
    cdsDiarioConsFC_VIATURA: TStringField;
    cdsDiarioConsclTurno: TStringField;
    dsDiarioCons: TDataSource;
    procedure dspDiarioUpdateError(Sender: TObject;
      DataSet: TCustomClientDataSet; E: EUpdateError;
      UpdateKind: TUpdateKind; var Response: TResolverResponse);
    procedure cdsDiarioBeforeDelete(DataSet: TDataSet);
    procedure cdsDiarioViaturaCalcFields(DataSet: TDataSet);
    procedure DataModuleCreate(Sender: TObject);
    procedure cdsDiarioConsCalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
    vUsuario: String;
    ctViatura: String;
    ctDiario: String;
    procedure prcLocalizar(vId: Integer);
  end;

implementation

uses UDm1;

{$R *.dfm}

procedure TdmDiario.dspDiarioUpdateError(Sender: TObject; DataSet: TCustomClientDataSet; E: EUpdateError; UpdateKind: TUpdateKind;
  var Response: TResolverResponse);
begin
  raise Exception.Create(E.Message);
end;

procedure TdmDiario.cdsDiarioBeforeDelete(DataSet: TDataSet);
begin
{  while not cdsDiarioAlarme.IsEmpty do
    cdsDiarioAlarme.Delete;
  while not cdsDiarioBairro.IsEmpty do
    cdsDiarioBairro.Delete;
  while not cdsDiarioCamera.IsEmpty do
    cdsDiarioCamera.Delete;
  while not cdsDiarioEspecial.IsEmpty do
    cdsDiarioEspecial.Delete;
  while not cdsDiarioRonda.IsEmpty do
    cdsDiarioRonda.Delete;
  while not cdsDiarioViatura.IsEmpty do
    cdsDiarioViatura.Delete;
  while not cdsDiarioPortaria.IsEmpty do
    cdsDiarioPortaria.Delete;
  while not cdsDiarioCelular.IsEmpty do
    cdsDiarioCelular.Delete;}
end;

procedure TdmDiario.cdsDiarioViaturaCalcFields(DataSet: TDataSet);
begin
  if (cdsDiarioViaturaKM_FINAL.AsInteger > 0) and (cdsDiarioViaturaKM_INICIAL.AsInteger > 0) then
    cdsDiarioViaturaclKmTotal.AsInteger := cdsDiarioViaturaKM_FINAL.AsInteger - cdsDiarioViaturaKM_INICIAL.AsInteger;   
end;

procedure TdmDiario.DataModuleCreate(Sender: TObject);
begin
  ctDiario  := sdsDiario.CommandText;
  ctViatura := sdsViatura.CommandText;
end;

procedure TdmDiario.cdsDiarioConsCalcFields(DataSet: TDataSet);
begin
  if not cdsDiarioConsTURNO.IsNull then
    case cdsDiarioConsTURNO.AsInteger of
      1: cdsDiarioConsclTurno.AsString := '07:00 às 19:00';
      2: cdsDiarioConsclTurno.AsString := '19:00 às 07:00';
    end;
end;

procedure TdmDiario.prcLocalizar(vId: Integer);
begin
  cdsDiario.Close;
  sdsDiario.CommandText := 'SELECT D.*, D.ID AS DIARIO_ID FROM DIARIO D WHERE D.ID = ' + IntToStr(vId);
  cdsDiario.Open;
end;

end.
